# ------------------------------
# 博客基础配置
# ------------------------------
theme: jekyll-theme-chirpy
lang: zh-CN
timezone: Asia/GuangDong
title: Haru
tagline: 生活日常记录
description: 完成一次作业
url: "https://haruea.github.io"


# ------------------------------
# 个人信息&联系方式
# ------------------------------
social:
  name: Haru
  email: 485277361@qq.com
  links:
    - QQ: 485277361
    - 微信: Larseazin716


# ------------------------------
# 功能配置（仅保留基础项）
# ------------------------------
avatar: /assets/avatar.jpg  # 对应你assets里的头像文件名
location: 广东
toc: true  # 若不需要文章目录，可改成false
theme_mode: light
paginate: 10
comments:
  provider:  # 留空关闭评论功能
