# 1. 博客基础信息
title: Haru的生活日记
description: 希望我能做好这个博客
url: https://haruea.github.io

# 2. 你的个人信息
author:
  name: Haru
  bio: 一个爱听歌且热衷于打游戏的大学生
  avatar: /assets/avatar.jpg

# 3. 其他配置
markdown: kramdown
theme: minima
permalink: /posts/:title/
